In [34]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [35]:
df = pd.read_csv("./data/merged/merged_dataset.csv")

In [36]:
df

,review_id,author,rating,text
0,Ci9DQUlRQUNvZENodHljRjlvT21kZlYwazRNRFY2ZW5sTG...,Piyawat Jirapatwong,5,ไปทานบุฟซีฟู้ดมื้อเย็น🦞🦐 คิดว่าราคานี้ได้คุณภา...
1,ChdDSUhNMG9nS0VJQ0FnSUR2bllhbnRnRRAB,Chic Lerts,4,มาทานมื้อเที่ยงวันอาทิตย์ อาหารหลากหลายมากคุณภ...
2,ChdDSUhNMG9nS0VNZW1udTc1MzR5ajZ3RRAB,Ben Tordamrong,5,บุฟเฟ่ต์ราคาดี บน โรงแรม Eastin Sathon ด้วยตัว...
3,ChdDSUhNMG9nS0VJQ0FnSUNfb3VTa3NBRRAB,Daniel L,3,We came here for a buffet lunch at about 1pm. ...
4,ChdDSUhNMG9nS0VJQ0FnTURRNy16RGpBRRAB,แม่ก้าว,3,อาหารที่อร่อยสุดจะเป็นก๋วยเตี๋ยวเนื้อวากิว นอก...
...,...,...,...,...
3433,ChdDSUhNMG9nS0VJQ0FnSUMwcnJUXzVnRRAB,Kukki C.,2,วัตถุดิบธรรมดา ถ้าเทียบกับราคา ถือว่าไม่ค่อยคุ...
3434,ChZDSUhNMG9nS0VJQ0FnSURYcE9ucENBEAE,Boonyarit T.,4,อร่อยหลายอย่างตัด1คะแนนเนื้อไม่ผ่่านคับ
3435,ChZDSUhNMG9nS0VJQ0FnSURzOU1PMUZ3EAE,sun shy,3,อาหารต่างๆไม่ค่อยสด ทั้งกุ้งโบตั๋น ปลาแซลม่อน ...
3436,ChdDSUhNMG9nS0VJQ0FnSURnOWV2cTNRRRAB,Nayos T.,1,This review is for the location at seen space ...
3437,Ci9DQUlRQUNvZENodHljRjlvT201T1gyTlNRell5Vmxabl...,naja TW,5,อาหารสด อร่อย บริการดี เสริฟไวมาก

In [40]:
df.groupby('rating').count()

        review_id  author  text
rating
1             366     366   366
2             102     102   102
3             285     285   285
4             721     721   721
5            1964    1964  1964

In [44]:
one_star_df = df[df['rating'] == 1]
two_star_df = df[df['rating'] == 2]
three_star_df = df[df['rating'] == 3]
four_star_df = df[df['rating'] == 4]
five_star_df = df[df['rating'] == 5]

In [43]:
one_star_df

,review_id,author,rating,text
55,ChZDSUhNMG9nS0VJQ0FnSUNldWNubVpnEAE,Prachai Siriratikul,1,อาหารไม่อร่อยอย่างที่อวยกันเลย อาหารไม่สด ซาซ...
63,ChZDSUhNMG9nS0VJQ0FnSURNdWZQalR3EAE,heyday business,1,เมื่อวาน4มค63โทรจองตอนประมาณ11:55 ไปกินตอนเที่...
103,ChZDSUhNMG9nS0VJQ0FnTURvczhDMGJnEAE,A* Luo,1,"The food was decent, but the overall experienc..."
107,Ci9DQUlRQUNvZENodHljRjlvT25oNGJGSm9ORzlxWTIxUV...,natthartath thongcharoen,1,เจอยางในอาหาร ส่งให้พนักงานดู พนักงานเป็นต่างด...
110,ChdDSUhNMG9nS0VLbVR0SkNScnF6UzNRRRAB,Shin,1,I was quite disappointed with the marinated cr...
...,...,...,...,...
3411,Ci9DQUlRQUNvZENodHljRjlvT21zd1NWSktUMXB5UW5Kel...,ธนัญชนก เทพวงษ์,1,ของไม่ตรงกับที่ดูหน้าร้านอยากกินเบคอนก็บอกเอาอ...
3415,Ci9DQUlRQUNvZENodHljRjlvT2xoaWIxSlphbWMyVDBaeE...,itsaret chokwichian,1,เจอกั๊งมีกลิ่นเหม็นมาก พนักงานต่างชาติบอกให้ย่...
3428,Ci9DQUlRQUNvZENodHljRjlvT2sxamFHMURaRnBDTWtSNF...,Nostox,1,I have never done review before but this time ...
3431,Ci9DQUlRQUNvZENodHljRjlvT201eGFFWnplRk5pVnpFel...,สายฝน มนุชรังษี,1,แคชเชียร์พูดไม่เข้าใจ อธิบายก็ไม่รู้เรื่อง แล้...
3436,ChdDSUhNMG9nS0VJQ0FnSURnOWV2cTNRRRAB,Nayos T.,1,This review is for the location at seen space ...

In [46]:
two_star_df

,review_id,author,rating,text
57,ChdDSUhNMG9nS0VJQ0FnSURXNHFUbG53RRAB,T M,2,เมื่อก่อนโอเคเลยนะ ครั้งนี้ผิดหวังมาก\nราคาแพง...
102,Ci9DQUlRQUNvZENodHljRjlvT2xoWldsWTNSamxZVjJwRm...,Tony Khoo,2,Firstly this place is really expensive. Ordere...
136,ChdDSUhNMG9nS0VJQ0FnSUNReE95RHp3RRAB,Panghom Jaa,2,ร้านอาหารเกาหลีใจกลางเมือง ภายในร้านค่อนข้างแค...
173,ChdDSUhNMG9nS0VKZnZvWnZVanJ5d3NnRRAB,Sirithana K,2,พนักงานปิ้งไม่ดี เหมือนจะให้รีบๆ กินแล้วรีบๆ อ...
197,ChdDSUhNMG9nS0VJQ0FnSUNta1BpMnJnRRAB,Esmond Tan,2,Food and service is good. Portion is small and...
...,...,...,...,...
3365,ChdDSUhNMG9nS0VJQ0FnSUNSaG96RHBRRRAB,Phonpot Kitsampankul,2,คัณภาพอาหารกับราคามันก็โอเค แต่สิ่งที่ทำให้ลูก...
3398,ChZDSUhNMG9nS0VJQ0FnSURXcWRmU0tnEAE,Tan T.,2,Just so so. 😑\nToo pricey for the quality.\n\n...
3405,ChdDSUhNMG9nS0VJQ0FnTUNRME1yWXVBRRAB,Wine&Food With Nuchy,2,อาหารทะเลส่วนใหญ่ไม่สด ลดคุณภาพอาหาร เสียใจที่...
3413,ChdDSUhNMG9nS0VJQ0FnSUQ2X3I2RmlBRRAB,Wasunun T,2,ล่าสุดไปทานวันเสาร์ที่ 25 กย. รอคิวประมาณ 1 ชม...
3433,ChdDSUhNMG9nS0VJQ0FnSUMwcnJUXzVnRRAB,Kukki C.,2,วัตถุดิบธรรมดา ถ้าเทียบกับราคา ถือว่าไม่ค่อยคุ...

In [47]:
three_star_df

,review_id,author,rating,text
3,ChdDSUhNMG9nS0VJQ0FnSUNfb3VTa3NBRRAB,Daniel L,3,We came here for a buffet lunch at about 1pm. ...
4,ChdDSUhNMG9nS0VJQ0FnTURRNy16RGpBRRAB,แม่ก้าว,3,อาหารที่อร่อยสุดจะเป็นก๋วยเตี๋ยวเนื้อวากิว นอก...
24,ChdDSUhNMG9nS0VJQ0FnSURlX3RDS3lRRRAB,Yen Lee,3,ห้องอาหารอยู่ในโรงแรมอีสติน แกรน สาธร ตั้งใจไป...
29,ChZDSUhNMG9nS0VMYWpncWY2dzhESEJBEAE,Silapop Pilasruksakun,3,อาหารกลางๆอร่อยดี\nแต่พอดีไปสัมมนาหลานวัน\nกิน...
36,ChdDSUhNMG9nS0VJQ0FnSUNBajdLbWtBRRAB,Karnjanart C Wattana,3,ได้มาทานอาหารเย็นที่นี่ เป็นธรรมดาของถ.สาธร รถ...
...,...,...,...,...
3421,ChdDSUhNMG9nS0VJQ0FnSUQ2cF9ueGtnRRAB,mj moowan,3,กลับมาครั้งนี้ อาหารค่อยข้างมีขนาดที่เล็กลง ไม...
3424,ChdDSUhNMG9nS0VJQ0FnSUR5NWFlcDNRRRAB,Pan Pitak,3,“สาย buffet ท่ีต้องการความหลากหลาย อยากทั้งปิ้...
3426,ChZDSUhNMG9nS0VJQ0FnSUNHaDlMOUtBEAE,Nan PockyLuv,3,"บุฟเฟต์ 899\nรสชาติอร่อย กุ้งแม่น้ำสด, เนื้อดี..."
3429,ChZDSUhNMG9nS0VJQ0FnSURSMWR5TFpBEAE,Teesit Makapunyo,3,There is a lot of variety of food but the qual...
3435,ChZDSUhNMG9nS0VJQ0FnSURzOU1PMUZ3EAE,sun shy,3,อาหารต่างๆไม่ค่อยสด ทั้งกุ้งโบตั๋น ปลาแซลม่อน ...

In [48]:
four_star_df

,review_id,author,rating,text
1,ChdDSUhNMG9nS0VJQ0FnSUR2bllhbnRnRRAB,Chic Lerts,4,มาทานมื้อเที่ยงวันอาทิตย์ อาหารหลากหลายมากคุณภ...
5,ChZDSUhNMG9nS0VJQ0FnSURIc3NMQ053EAE,JackPawat B,4,13.10.2024\nSunday bruch อาหารหลากหลายมีปลาหิม...
7,ChZDSUhNMG9nS0VJQ0FnSUM1c3F5TGFBEAE,Thananont Krittayawiwat,4,ห้องอาหาร The Glass House ชั้น5 ที่ Eastin Gra...
10,ChdDSUhNMG9nS0VJQ0FnSURmeW9xdW13RRAB,Ann P,4,"Weekend Saturday dinner or Sunday lunch, inter..."
12,ChdDSUhNMG9nS0VJQ0FnSUNINk1iUG1RRRAB,Nat Lim,4,อาหารโอเค ชอบปลาหิมะนึ่งซีอิ๊ว ซาชิมิ ส่วนล็อบ...
...,...,...,...,...
3417,ChZDSUhNMG9nS0VJQ0FnSUNpNEpMalFBEAE,Sila Inkrai,4,น้องชวนไปกินมันบอกว่าดี\nความรู้สึกว่าโต๊ะแคบไ...
3419,ChdDSUhNMG9nS0VJQ0FnSUN3Mk8tdHRnRRAB,ภรภัทร ปิติโชตินันท์,4,อาหารอร่อย สด แยกเป็นย่างเอง หรือให้เชฟย่าง เพ...
3420,ChZDSUhNMG9nS0VJQ0FnSUNoNVAtX1h3EAE,Nit Cha,4,อยู่ชั้น 4 ในเซ็นทรัลพระราม 2 อร่อยดี มีบุฟเฟ่...
3432,Ci9DQUlRQUNvZENodHljRjlvT2twc2VuQnlSRVEzVVVsNG...,Surawee Denninnart1,4,มากับที่บ้าน กินวันพ่อ ซื้อเป็นคูปองมากินจากแอ...
3434,ChZDSUhNMG9nS0VJQ0FnSURYcE9ucENBEAE,Boonyarit T.,4,อร่อยหลายอย่างตัด1คะแนนเนื้อไม่ผ่่านคับ

In [49]:
five_star_df

,review_id,author,rating,text
0,Ci9DQUlRQUNvZENodHljRjlvT21kZlYwazRNRFY2ZW5sTG...,Piyawat Jirapatwong,5,ไปทานบุฟซีฟู้ดมื้อเย็น🦞🦐 คิดว่าราคานี้ได้คุณภา...
2,ChdDSUhNMG9nS0VNZW1udTc1MzR5ajZ3RRAB,Ben Tordamrong,5,บุฟเฟ่ต์ราคาดี บน โรงแรม Eastin Sathon ด้วยตัว...
6,ChdDSUhNMG9nS0VJQ0FnSUNYcXZuOG1BRRAB,Din Neo,5,Very tasty and delicious food! The buffet spre...
8,ChdDSUhNMG9nS0VJQ0FnSUNfbjRuQ3JBRRAB,AngAng Ang,5,บุฟเฟ่ต์กลางวัน วันธรรมดา\nอาหารมีหลากหลาย sea...
9,ChdDSUhNMG9nS0VJQ0FnSURyMC1fNXNnRRAB,Jubilee Joob,5,มากิน 3 รอบแล้ว บุฟเฟต์มื้อกลางวัน มีล้อปสเตอร...
...,...,...,...,...
3423,ChdDSUhNMG9nS0VJQ0FnTURnd3V1bndnRRAB,Oiru Azxault,5,เหมาะสำหรับเพื่อนมากินด้วยกัน อาหารเสิร์ฟค่อนข...
3425,ChdDSUhNMG9nS0VJQ0FnTUNRdFA2XzRRRRAB,Kanka Pram,5,บุฟเฟต์ 999.- อร่อย สด พนักงานน่ารัก คือ ดีงาม...
3427,Ci9DQUlRQUNvZENodHljRjlvT2taU1NtcExkSE5wVG5oam...,Boonsita,5,อร่อยมากค่ะ เมนูเยอะมากกก
3430,ChZDSUhNMG9nS0VJQ0FnTURnNk4zMlhBEAE,Chayanee Toxkangwan,5,The service was excellent! And the food was gr...
3437,Ci9DQUlRQUNvZENodHljRjlvT201T1gyTlNRell5Vmxabl...,naja TW,5,อาหารสด อร่อย บริการดี เสริฟไวมาก

In [50]:
test_df = pd.concat([one_star_df[0:100], two_star_df[0:100], three_star_df[0:100], four_star_df[0:100], five_star_df[0:100]])

In [52]:
test_df.to_csv("test_set_no_label.csv")